# Generated by Django 2.2.3 on 2019-07-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='name',
            new_name='nickname',
        ),
    ]
