# Generated by Django 2.2.3 on 2019-07-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190721_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='nickname',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
