# Generated by Django 2.2.3 on 2019-07-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190727_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
