# Generated by Django 2.2.3 on 2019-07-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=1000)),
                ('media', models.ImageField(blank=True, default='', upload_to='posts/')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
