# Generated by Django 2.2.3 on 2019-07-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190725_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
