# Generated by Django 2.2.3 on 2019-07-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
