# Generated by Django 2.2.3 on 2019-07-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
