# Generated by Django 2.2.3 on 2019-08-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
