# Generated by Django 2.2.3 on 2019-08-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190801_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='description',
        ),
    ]
