# Generated by Django 2.2.3 on 2019-08-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190801_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='reply',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
