# Generated by Django 2.2.3 on 2019-08-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190804_0123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
