# Generated by Django 2.2.3 on 2019-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_title', models.TextField()),
                ('q_content', models.TextField()),
                ('q_created', models.DateTimeField(auto_now_add=True)),
                ('q_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-q_created'],
            },
        ),
        migrations.CreateModel(
            name='Q_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_reply', models.TextField(max_length=200)),
                ('q_c_created', models.DateTimeField(auto_now_add=True)),
                ('q_c_updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete='CASCADE', to='question.Question')),
            ],
        ),
    ]
