# Generated by Django 2.2.3 on 2019-08-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_q_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='q_comment',
            name='author_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='q_comment',
            name='author_username',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='author_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='author_username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
