# Generated by Django 2.2.3 on 2019-08-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20190808_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_comment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_comment_set', to='question.Question'),
        ),
    ]
