# Generated by Django 2.2.3 on 2019-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('gps', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=200)),
                ('c_created', models.DateTimeField(auto_now_add=True)),
                ('c_updated', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete='CASCADE', to='blog.Blog')),
            ],
            options={
                'ordering': ['-c_created'],
            },
        ),
    ]
