# Generated by Django 2.2.3 on 2019-07-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('like', models.IntegerField(blank=True, default=0)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('gps', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=200)),
                ('posting', models.ForeignKey(on_delete='CASCADE', to='blog.Posting')),
            ],
        ),
    ]
