# Generated by Django 2.2.3 on 2019-07-28 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posting',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='blog.Posting'),
        ),
    ]
