# Generated by Django 2.2.3 on 2019-07-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190728_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='gps',
        ),
        migrations.AddField(
            model_name='posting',
            name='cocoment',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='gps1',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='gps2',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=19),
            preserve_default=False,
        ),
    ]
