# Generated by Django 2.2.3 on 2019-07-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190726_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
