# Generated by Django 2.2.3 on 2019-07-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190727_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={},
        ),
        migrations.RemoveField(
            model_name='posting',
            name='content',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='created',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='like',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='updated',
        ),
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
