# Generated by Django 2.2.3 on 2019-07-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190727_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='author',
        ),
    ]
