# Generated by Django 2.2.3 on 2019-07-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_posting_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='c_created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='c_updated',
        ),
    ]
