# Generated by Django 2.2.3 on 2019-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190728_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='author',
        ),
        migrations.AddField(
            model_name='posting',
            name='author_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='author_username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
