# Generated by Django 2.2.3 on 2019-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190728_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='posting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
