# Generated by Django 2.2.3 on 2019-08-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190728_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
