# Generated by Django 2.2.3 on 2019-08-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190801_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
