# Generated by Django 2.2.3 on 2019-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190803_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='photo',
            field=models.FileField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
