# Generated by Django 2.2.3 on 2019-08-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190804_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='likedusers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
