# Generated by Django 2.2.3 on 2019-08-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20190804_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='likedusers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
