# Generated by Django 2.2.3 on 2019-08-05 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20190804_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='blog.Posting'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
