# Generated by Django 2.2.3 on 2019-08-06 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0033_auto_20190805_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lovecnt', models.IntegerField(blank=True, default=0)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Posting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
