# Generated by Django 2.2.3 on 2019-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20190807_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='count',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='likedusers',
        ),
        migrations.AlterField(
            model_name='like',
            name='likeCnt',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
