# Generated by Django 2.2.3 on 2019-08-07 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0036_auto_20190807_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='posting',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='postingId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postingId', to='blog.Posting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userId_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
