# Generated by Django 2.2.3 on 2019-08-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20190807_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
